export const report_data = [
  {
    "id": 1,
    "opinion": "First opinion",
    "requested_date": "2026-01-09",
    "satisfaction": 1,
    "user_id": 3
  }, {
    "id": 2,
    "opinion": "",
    "requested_date": "2026-01-09",
    "satisfaction": 1,
    "user_id": 1
  }, {
    "id": 3,
    "opinion": "",
    "requested_date": "2026-01-09",
    "satisfaction": 2,
    "user_id": 1
  }, {
    "id": 4,
    "opinion": "",
    "requested_date": "2026-01-09",
    "satisfaction": 2,
    "user_id": 1
  }, {
    "id": 5,
    "opinion": "",
    "requested_date": "2026-01-09",
    "satisfaction": 1,
    "user_id": 4
  }, {
    "id": 6,
    "opinion": "",
    "requested_date": "2026-01-09",
    "satisfaction": 2,
    "user_id": 5
  }, {
    "id": 7,
    "opinion": "",
    "requested_date": "2026-01-12",
    "satisfaction": 2,
    "user_id": 6
  }, {
    "id": 8,
    "opinion": "",
    "requested_date": "2026-01-12",
    "satisfaction": 1,
    "user_id": 1
  }, {
    "id": 9,
    "opinion": "",
    "requested_date": "2026-01-12",
    "satisfaction": 1,
    "user_id": 1
  }, {
    "id": 10,
    "opinion": "",
    "requested_date": "2026-01-12",
    "satisfaction": 2,
    "user_id": 7
  }, {
    "id": 11,
    "opinion": "",
    "requested_date": "2026-01-12",
    "satisfaction": 1,
    "user_id": 1
  }, {
    "id": 12,
    "opinion": "",
    "requested_date": "2026-01-13",
    "satisfaction": 1,
    "user_id": 1
  }]